name: Delete Commit Records Weekly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  delete-commit-records:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Delete commit records
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git checkout --orphan new_branch
        git commit -m "init"
        git branch -D main
        git branch -m main
        git push -f origin main 
